#include <catch2/catch.hpp>

TEST_CASE("Failing test-case") {
  CHECK(false);
}
